# -*- coding: utf-8 -*-
"""AI lab-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dEFuc3szW_rduMYDeYAPHWkSqSTWSHay
"""

lst=["dog","cat","fox"]
print(lst)
print(type(lst))
lst1=[1,2,3,4,5]
print(lst1)

lst=[1.0,"dog",True]
print(lst)

lst=["cow",12,True]
print(lst[1])
print(lst[-1])

l = ["apple", "banana", "cherry", "Guava", "kiwi", "melon", "mango"]
print(l[2:5])
print(l[-4:-1])
l[1] = "blackcurrant"
print(l)
l.insert(2, "watermelon")
print(l)
l.append("orange")
print(l)
tropical = ["mango", "pineapple", "papaya"]
l.extend(tropical)
print(l)
l.pop(1)
print(l)
for x in l:
  print(x)

f=open("demo.txt","r")
print(f.read())